package com.resumescreener.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a summarized version of a resume.
 * Generated by abstractive summarization model (e.g., facebook/bart-large-cnn).
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class SummarizedResume {

    @JsonProperty("summary_text")
    private String summaryText;

    @JsonProperty("confidence_score")
    private double confidenceScore;  // 0.0 - 1.0

    @JsonProperty("word_count")
    private int wordCount;

    @JsonProperty("compression_ratio")
    private double compressionRatio;  // original_length / summary_length

    @JsonProperty("generated_at")
    private long generatedAtMs;

    @JsonProperty("model_name")
    private String modelName;

    @JsonProperty("was_fallback")
    private boolean wasFallback;  // true if fallback due to model unavailability
}
